# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('ifsc_code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 5, 4, 19, 15, 22, 768853))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 5, 4, 19, 15, 22, 768901))),
            ],
        ),
    ]
