# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 19, 24, 12, 964669)),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 19, 24, 12, 964720)),
        ),
    ]
