# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0002_auto_20170504_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='name',
            field=models.CharField(default='Kukatpally', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
