# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account_number', models.CharField(max_length=12)),
                ('to_account_number', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Declined'), (2, 'Aborted'), (3, 'Successful')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
