# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transferprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferprocess',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Timed out'), (2, 'Successful'), (3, 'Invalid')], default=0),
        ),
        migrations.AddField(
            model_name='transferprocess',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 0, 26, 49, 873717, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
