# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='grid',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'a': 'nune'}),
            preserve_default=False,
        ),
    ]
