# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0002_auto_20170504_1924'),
        ('accounts', '0003_auto_20161117_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankbranch.BankBranch'),
            preserve_default=False,
        ),
    ]
